<?php 
// retrieve identity
use Zend\Authentication\AuthenticationService;

/*$authService = new AuthenticationService();
if ($authService->hasIdentity()) {
	$name = $authService->getIdentity()->email;
} else {
	$name = 'guest';
}*/

$authService = new AuthenticationService();
if ($authService->hasIdentity()) {
    $ldap = $authService->getIdentity();
    $bind = $ldap->getBoundUser();
    $fullEntry = $ldap->getEntry($bind);
    $name = ucfirst($fullEntry['cn'][0]) . ' ' . ucfirst($fullEntry['sn'][0]);
} else {
    $name = 'guest';
}

// HTML stuff
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = 'http://' . $_SERVER['HTTP_HOST'];
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2widder Application') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <!-- use the "url('home') method to create a link to the 'home' route -->
          <a class="brand" href="<?php echo $basePath; ?>">ZF2widder Application</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $basePath; ?>">Home</a></li>
			  <?php if ($name == 'guest') : ?>
				<li class="active"><a href="<?php echo $basePath; ?>/login">Login</a></li>
			  <?php else : ?>
				<li class="active"><a href="<?php echo $basePath; ?>/logout">Logout</a></li>
              	<li class="active"><a href="<?php echo $basePath; ?>/post">Post</a></li>
			  <?php endif; ?>
			  <?php //if ($name == 'admin@zend.com') : ?>
              	<!-- <li class="active"><a href="<?php //echo $basePath; ?>/admin">Admin</a></li> -->
              <?php //endif; ?>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
    
	  Welcome <b><?php echo $name; ?></b>
      <?php echo $this->content; ?>

      <div class="footer">
        <hr />
        &copy; 2006 - 2013 by Zend Technologies Ltd. All rights reserved.
        &nbsp;&nbsp;Zend Framework Version: <?php echo Zend\Version\Version::VERSION; ?>
	  </div>
	  
    </div> <!-- /container -->
	<div style="display:none;">
	
  </body>
</html>
