<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                         => __DIR__ . '/Module.php',
    'Admin\Service\UsersTableFactory'      => __DIR__ . '/src/Admin/Service/UsersTableFactory.php',
    'Admin\Service\IndexControllerFactory' => __DIR__ . '/src/Admin/Service/IndexControllerFactory.php',
    'Admin\Service\UserService'            => __DIR__ . '/src/Admin/Service/UserService.php',
    'Admin\Model\UsersTable'               => __DIR__ . '/src/Admin/Model/UsersTable.php',
    'Admin\Controller\IndexController'     => __DIR__ . '/src/Admin/Controller/IndexController.php',
    'Admin\Form\InArray'                   => __DIR__ . '/src/Admin/Form/InArray.php',
    'Admin\Form\UserDeleteFilter'          => __DIR__ . '/src/Admin/Form/UserDeleteFilter.php',
    'Admin\Form\UserInfoForm'              => __DIR__ . '/src/Admin/Form/UserInfoForm.php',
    'Admin\Form\UserDeleteForm'            => __DIR__ . '/src/Admin/Form/UserDeleteForm.php',
    'Admin\Form\UserInfoFilter'            => __DIR__ . '/src/Admin/Form/UserInfoFilter.php',
    'ModuleTest'                           => __DIR__ . '/tests/Admin/ModuleTest.php',
    'UsersTableTest'                       => __DIR__ . '/tests/Admin/Model/UsersTableTest.php',
);
